site_name: The moment
site_url: https://ottokafka2.github.io/leave/
nav:
  - Home: index.md
  - Diaries:
      - 2023:
          - Auguest:
            - 我的倒计时: diaries/2023/auguest/one_day_home_away.md
            - 困境: diaries/2023/auguest/inescapable_dreams.md
            - 起飞: diaries/2023/auguest/depatures.md
            - 多变的天气: diaries/2023/auguest/changeable_weather.md
          - September:
            - 错误: diaries/2023/september/mistakes.md
      - 2024:
          - January:
            - A Talk: diaries/2024/january/talk.md
          - Faburary:
            - The Office: diaries/2024/feburary/theOffice.md
            - Monster: diaries/2024/feburary/monster.md
            - Alter: diaries/2024/feburary/alter.md
            - Year Of Dragon: diaries/2024/feburary/year_of_dragon.md
            - Brilliant Weather: diaries/2024/feburary/brilliant_weather.md
            - A lesson: diaries/2024/feburary/a_lesson.md
            - Rain Drop: diaries/2024/feburary/raindrop.md
            - Birthday Party: diaries/2024/feburary/birthday.md
          - March:
            - Grandma: diaries/2024/march/grandma.md
theme:
  name: material
  highlightjs: true
  palette:
    scheme: default
    primary: deep orange
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path